stages:
  pre_process:
    cmd: python3 src/pre_process.py
    deps:
      - src/pre_process.py
      - data/raw/rML-raw-data.csv
    params:
      - pre_process
    outs:
      - data/processed/rML-test.csv
      - data/processed/rML-train.csv
  train:
    cmd: python3 src/train.py
    deps:
      - src/model_def.py
      - data/processed/rML-train.csv
      - src/train.py
    params:
      - train
    outs:
      - models/model.pkl
    metrics:
      - models/metrics/train.yaml:
          cache: false
  eval:
    cmd: python3 src/evaluate.py
    deps:
      - src/evaluate.py
      - models/model.pkl
      - data/processed/rML-test.csv
    params:
      - pre_process
      - train
    metrics:
      - models/metrics/test.yaml:
          cache: false
