stages:
  preprocessing:
    cmd: python3 src/preprocess.py
    deps:
      - general_params.yml
      - src/preprocess.py
      - data/raw/rML-raw-data.csv
    outs:
      - data/processed/rML-test.csv
      - data/processed/rML-train.csv
  training:
    cmd: python3 src/training.py
    deps:
      - general_params.yml
      - src/model_def.py
      - data/processed/rML-train.csv
      - src/training.py
    outs:
      - models:
          persist: true
      - params.yml:
          cache: false
          persist: true
    metrics:
      - training_metrics.csv:
          cache: false
  eval:
    cmd: python3 src/evaluate.py
    deps:
    - src/evaluate.py
    - general_params.yml
    - model_params.yml
    - models
    - data/processed/rML-test.csv
    metrics:
    - test_metrics.csv:
        cache: false
