feature_type: text
model__alpha: 0.0001
model__average: false
model__class_weight: null
model__early_stopping: false
model__epsilon: 0.1
model__eta0: 0.0
model__fit_intercept: true
model__l1_ratio: 0.15
model__learning_rate: optimal
model__loss: log
model__max_iter: 1000
model__n_iter_no_change: 5
model__n_jobs: null
model__penalty: l2
model__power_t: 0.5
model__random_state: 42
model__shuffle: true
model__tol: 0.001
model__validation_fraction: 0.1
model__verbose: 0
model__warm_start: false
model_class: SGDClassifier
tfidf__analyzer: word
tfidf__binary: false
tfidf__decode_error: strict
tfidf__dtype: <class 'numpy.float64'>
tfidf__encoding: utf-8
tfidf__input: content
tfidf__lowercase: true
tfidf__max_df: 1.0
tfidf__max_features: 25000
tfidf__min_df: 1
tfidf__ngram_range: (1, 1)
tfidf__norm: l2
tfidf__preprocessor: null
tfidf__smooth_idf: true
tfidf__stop_words: null
tfidf__strip_accents: null
tfidf__sublinear_tf: false
tfidf__token_pattern: (?u)\b\w\w+\b
tfidf__tokenizer: null
tfidf__use_idf: true
tfidf__vocabulary: null
